spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: false

booking:
  service:
    external:
      host: ${BOOKING_SERVICE_EXTERNAL_HOST:booking-service}
      port: ${BOOKING_SERVICE_EXTERNAL_PORT:9090}
