version: '3.8'

services:
  apollo-gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - booking-subgraph
      - hotel-subgraph
    networks:
      - hotelio-net

  booking-subgraph:
    build: ./booking-subgraph
    ports:
      - "4001:4001"
    depends_on:
      - booking-service
    networks:
      - hotelio-net

  hotel-subgraph:
    build: ./hotel-subgraph
    ports:
      - "4002:4002"
    networks:
      - hotelio-net

  # Добавляем booking-service из task2
  booking-service:
    build:
      context: ../task2/booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "9090:9090"
    networks:
      - hotelio-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-db:5432/booking_service
      SPRING_DATASOURCE_USERNAME: booking
      SPRING_DATASOURCE_PASSWORD: booking
    depends_on:
      - booking-db

  booking-db:
    image: postgres:15
    container_name: booking-db
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking_service
    ports:
      - "5433:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

networks:
  hotelio-net:
    driver: bridge

volumes:
  booking-db-data:
